#GENERAL
REPOSITORY_TYPE = 'json'


#FOR JSON USES
ENCODING_TYPE = 'utf8'
BASE_INDENT = 2
ENSURE_ASCII = False

#FOR ORDERS
INITIAL_ORDERS_NUMBER = 100

#ORDER_STATUS_CONSTANTS
STATUS_OPEN = 'aberto'
STATUS_COMPLETED = 'finalizado'
STATUS_CANCELED = 'cancelado'

ALLOWED_ORDER_STATUSES = {
    STATUS_OPEN,
    STATUS_COMPLETED,
    STATUS_CANCELED,
}